# Generated by Django 4.1.5 on 2023-05-21 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='registration',
            name='address2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='registration',
            name='subscription',
            field=models.BooleanField(choices=[(True, 'Evet'), (False, 'Hayır')], default=False),
        ),
    ]
