# Generated by Django 4.1.5 on 2023-05-21 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_country_region_alter_registration_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
