# Generated by Django 4.1.5 on 2023-05-21 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_registration_subscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
